exclude:
  - ci
  - azure-pipelines.yml
  - .gitignore
  - .editorconfig
  - Dockerfile
  - Dockerfile.web
  - docker-compose.yml
  - docker-compose-ci.yml
  - docker-start.sh
  - docker-ci.sh
  - README.md
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"

  